### ISSUE TITLE
error on nonframeshift deletion

### ISSUE THREAD

**Issue by mpallocc** [openvax/varcode#246]
Dear all,

we are experiencing this error on a non-frameshift deletion, ending with a stopgain (quite rare): 

protein change: p.V340_*358del

varcode definition: 

vv = Variant(contig=16, start=30128111, ref='CTGGGGTGGTAGAGACAGCAAGGCTCAGGCCTGGCATGGGGGATGCCTACGTGCCCCCCTGCTCCCCTGCCCCCAGCCCCACTGCTGCTGGGGACTGGCCCAC', alt='', ensembl='GRCh37')

>>> vv.effects()
INFO:varcode.effects.effect_prediction:Mutation in variant Variant(contig='16', start=30128112, ref='CTGGGGTGGTAGAGACAGCAAGGCTCAGGCCTGGCATGGGGGATGCCTACGTGCCCCCCTGCTCCCCTGCCCCCAGCCCCACTGCTGCTGGGGACTG', alt='', reference_name='GRCh37') starts before exon Exon(exon_id='ENSE00001520895', gene_id='ENSG00000102882', gene_name='MAPK3', contig='16', start=30128158, end=30128324, strand='-')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/varcode/variant.py", line 452, in effects
    variant=self, raise_on_error=raise_on_error)
  File "/usr/local/lib/python2.7/dist-packages/varcode/effects/effect_prediction.py", line 96, in predict_variant_effects
    transcript=transcript)
  File "/usr/local/lib/python2.7/dist-packages/varcode/effects/effect_prediction.py", line 215, in predict_variant_effect_on_transcript
    variant, exon, exon_number, transcript)
  File "/usr/local/lib/python2.7/dist-packages/varcode/effects/effect_prediction.py", line 392, in exonic_transcript_effect
    transcript_offset=transcript_offset)
  File "/usr/local/lib/python2.7/dist-packages/varcode/effects/effect_prediction_coding.py", line 122, in predict_variant_coding_effect_on_transcript
    sequence_from_start_codon=sequence_from_start_codon)
  File "/usr/local/lib/python2.7/dist-packages/varcode/effects/effect_prediction_coding_in_frame.py", line 239, in predict_in_frame_coding_effect
    aa_alt=aa_alt)
  File "/usr/local/lib/python2.7/dist-packages/varcode/effects/effect_classes.py", line 670, in __init__
    "If no amino acids added by StopLoss then it should be Silent")
ValueError: If no amino acids added by StopLoss then it should be Silent

Seems to instantiate a StopLoss object and it raises error from there.

**Comment by mpallocc** [comment]
any updates on this? thank you!

**Comment by iskandr** [comment]
The reproducer in this issue is a ref-vs-genome mismatch — the variant claims ref='C' at chr16:30128111 but the actual GRCh37 reference has 'G' there. As of varcode 2.2.1 (openvax/varcode#278), this now raises `varcode.ReferenceMismatchError` with a message explaining the likely causes rather than the opaque error that was reported here. If you have a reproducer where the ref genuinely matches the genome but varcode still errors, please open a new issue.
